-- Committed schema-drift evidence for the meal-planning schema.
--
-- Nothing executes this file. The executed ledger is
-- prisma/migrations/20260908000000_meal_planning/migration.sql; this is the
-- reviewed output of one command, committed so that the ledger and
-- prisma/schema.prisma cannot drift apart unnoticed.
--
-- THE COMMAND. Run from backend/, with SHADOW_DATABASE_URL naming a DISPOSABLE
-- database - the command resets the database it is given, so never the one
-- holding the applied ledger and never anything that matters:
--
--   npx prisma migrate diff \
--     --from-migrations prisma/migrations \
--     --to-schema-datamodel prisma/schema.prisma \
--     --shadow-database-url "$SHADOW_DATABASE_URL" \
--     --exit-code --script
--
-- Everything below this header is that command's output, byte for byte. It is
-- the whole of the file's payload: there is no second capture and no other
-- contract here.
--
-- EXIT CODE. --exit-code makes 2 the expected result: it means the datamodel
-- and the ledger differ, which is what the statement below records. 0 means
-- either that this file is stale - the two now agree and there is nothing left
-- to record - or that the construct the statement stands for is gone from the
-- migration. 1 means the command itself failed, usually an unreachable or
-- non-empty shadow database.
--
-- WHAT THE ONE STATEMENT IS. The migration creates catalog_foods.search_vector
-- as a STORED generated column, which prisma/schema.prisma can only carry as
-- Unsupported("tsvector")?. Prisma's schema describer reads a generated
-- expression through the column-default slot, so the difference it reports is
-- the loss of that default rather than the expression itself. Measured on this
-- tree: replacing the generated column with a plain tsvector column makes the
-- command print "This is an empty migration." and exit 0, so the gate's
-- exit-code requirement is what makes that loss loud.
--
-- WHAT THE PLAN ASKS OF THIS FILE, AND WHAT THE COMMAND CAN GIVE. Agent Action
-- Plan sections 0.5.1 and 0.9.1 specify this artefact as the committed output of
-- the command above, whose "only statements" are the three constructs the Prisma
-- datamodel cannot express: the generated search_vector expression, the
-- lower(alias) expression index on catalog_food_aliases, and the partial
-- indexes' predicates. The prohibition holds here - there is no statement in the
-- payload outside those three classes, which is what the gate enforces. The
-- expectation that all three appear does not hold, and cannot: measured against
-- prisma 6.9.0, the command reports the first class and nothing else.
--
-- This tree proves why, without tampering with anything. The migration creates
-- six indexes Prisma cannot express - the lower(alias) index and five partial
-- indexes - and prisma/schema.prisma declares no counterpart for any of them.
-- Were they visible on the migration side of the comparison, a diff toward a
-- datamodel that lacks them would have to emit six DROP INDEX statements. It
-- emits none, with --from-migrations and with --from-url against an already
-- migrated database alike, so Prisma's schema describer leaves those constructs
-- out of the schema it compares rather than finding them unchanged in it.
-- Tampering only confirms the consequence: deleting the lower(alias) index,
-- changing a partial unique index's predicate, or dropping NOT NULL from a
-- required array column each leave this output and the exit code untouched.
--
-- So the gap between the three classes the plan expects here and the one class
-- the specified command emits is an AAP-versus-tool conflict, recorded for
-- authorized resolution. It is NOT a reinterpretation of the contract, and it is
-- not closed by this file: closing it needs either an amendment naming a second,
-- approved mechanism for the expression index and the partial predicates, or a
-- tool that reports them. Do not close it by adding a capture of your own here -
-- a second contract inside this file is exactly what review rejected.
--
-- Until it is resolved, this gate polices the generated column and nothing else.
-- The nearest existing cover for the other two constructs - partial, and no
-- substitute for the plan's contract - is the ledger-equivalence gate,
-- describe('migration ledgers') in src/__tests__/api/compat.test.ts: it applies
-- the Prisma ledger and the operator copy under
-- prisma/manual-migrations/meal-planning/ and compares the resulting columns,
-- indexes and constraints, so one of the two losing a construct the other keeps
-- fails there. A construct dropped from both at once is caught by neither, and
-- reviewing the migration is the only thing that covers it.
--
-- THE GATE is the `Schema-drift evidence gate` step of
-- .github/workflows/ci.yml. It runs the command above against a throwaway
-- shadow database of its own, requires exit code 2, and then compares the
-- output with this file after deleting from both sides every line that begins
-- with `--` and every empty line (`sed '/^--/d;/^$/d'`) - and nothing else, so
-- whitespace inside or around a payload line is compared as content. It fails
-- on any difference in either direction, which makes an added statement as loud
-- as a removed one.
--
-- Fix a failure in prisma/schema.prisma and the migration, never by editing this
-- file to match - unless the change to those two was the intended one, in which
-- case re-run the command, replace the payload below with its output, and review
-- the new content.
--
-- Use line comments only, each starting at column 0. A block comment, or a `--`
-- that starts after a space, survives the strip above and is compared as
-- payload.
--
-- Captured against prisma and @prisma/client 6.9.0 on PostgreSQL 16.15, ledger
-- prisma/migrations through 20260908000000_meal_planning.

-- AlterTable
ALTER TABLE "catalog_foods" ALTER COLUMN "search_vector" DROP DEFAULT;
