-- Committed schema-drift evidence for the meal-planning schema: the captured
-- output of `prisma migrate diff` between the migration ledger and
-- prisma/schema.prisma, and nothing else.
--
-- Nothing executes this file. The executed ledger is
-- prisma/migrations/20260908000000_meal_planning/migration.sql; this is the
-- reviewed evidence of what that ledger holds and prisma/schema.prisma cannot
-- express, committed so that the ledger, the datamodel and the applied database
-- cannot drift apart unnoticed.
--
-- THE WHOLE FILE IS THE PAYLOAD. Agent Action Plan 0.5.1 and 0.9.1 specify this
-- artefact as that command's output and compare it as a whole: every line
-- beginning with `--` and every empty line is deleted from both sides
-- (`sed '/^--/d;/^$/d'`) and what remains is compared byte for byte, in both
-- directions - an added statement fails as loudly as a removed one. Whitespace
-- inside or around a statement is content. Everything above the payload is
-- therefore a line comment starting at column 0, and there are no section
-- markers of any kind: a block comment, or a `--` that starts after a space,
-- survives the strip and is compared as a statement.
--
-- REGENERATING, and the comparison itself. From backend/, with
-- SHADOW_DATABASE_URL naming a DISPOSABLE database - the command resets the
-- database it is given, so never the one holding the applied ledger and never
-- anything that matters:
--
--   set +e
--   npx prisma migrate diff \
--     --from-migrations prisma/migrations \
--     --to-schema-datamodel prisma/schema.prisma \
--     --shadow-database-url "$SHADOW_DATABASE_URL" \
--     --exit-code --script > /tmp/schema-diff.sql
--   rc=$?
--   set -e
--   test "$rc" -eq 2
--   diff <(sed '/^--/d;/^$/d' /tmp/schema-diff.sql) \
--        <(sed '/^--/d;/^$/d' docs/meal-planning/expected-schema-diff.sql)
--
-- --exit-code makes 2 the expected result: it means the datamodel and the
-- ledger differ, which is what this file records. 0 means either that this file
-- is stale - the two now agree - or that the construct its statement stands for
-- is gone from the migration. 1 means the command itself failed, usually an
-- unreachable or non-empty shadow database.
--
-- WHAT THE PAYLOAD COVERS, AND WHAT IT CANNOT. AAP 0.5.1 expects this output to
-- carry the three constructs the Prisma datamodel cannot express: the generated
-- search_vector expression, the lower(alias) expression index on
-- catalog_food_aliases, and the partial indexes' predicates. Measured against
-- prisma 6.9.0 it carries only the first - the statement below. Prisma's schema
-- describer leaves expression indexes, index predicates and scalar-list NOT
-- NULL out of both sides of its comparison, so deleting the lower(alias) index,
-- changing a partial index's predicate, or dropping NOT NULL from a required
-- array column each leave this output and its exit code untouched. That is a
-- recorded AAP-versus-tool divergence, and what closes the two classes the tool
-- omits is the separate pg_catalog evidence in
-- docs/meal-planning/schema-catalog-evidence.sql, whose header carries the
-- measurements behind it. The generated column is evidenced in both files on
-- purpose: here the exit-code requirement is what makes its loss loud, because
-- replacing it with a plain tsvector column makes the command print "This is an
-- empty migration." and exit 0.
--
-- A RED GATE is fixed in prisma/schema.prisma and the migration, never by
-- editing this file to match - unless the DDL change was the intended one, in
-- which case regenerate the capture with the command above, replace the payload
-- below with it verbatim, and review the new content.
--
-- THE GATE is the `Schema-drift evidence gate` step of
-- .github/workflows/ci.yml. It runs the command above against a throwaway
-- shadow database of its own, requires exit code 2, and compares this whole
-- file with the output; the same step polices schema-catalog-evidence.sql
-- beside it.
--
-- Captured against prisma and @prisma/client 6.9.0 on PostgreSQL 16.15, ledger
-- prisma/migrations through 20260908000000_meal_planning.

-- AlterTable
ALTER TABLE "catalog_foods" ALTER COLUMN "search_vector" DROP DEFAULT;
